### ISSUE TITLE
Allow flexible sorting with SaveData()

### ISSUE THREAD

**Issue by veli-m-andirin** [gslab-econ/gslab_r#12]
Currently SaveData() sorts the data based on the keys provided and saves. We'd like to allow specifying an optional sort variable. The default variables used for sorting will still be the keys.

**Comment by santiagohermo** [comment]
Since you are going to touch `SaveData`, let me flag that the data manifest doesn't compute the mean when there are missing numeric variables @veli-m-andirin

**Comment by veli-m-andirin** [comment]
Thanks @santiagohermo! Very good point.

One more note: Overwriting existing data_file_manifests.

**Comment by veli-m-andirin** [comment]
@jmshapir, could you please give me write access to this repo?

**Comment by jmshapir** [comment]
@veli-m-andirin it should now be done!

**Comment by veli-m-andirin** [comment]
In 7fdc1ba:

- I implemented flexible sorting. (The default for sorting is still using the keys provided.)
- Added a small test function to ensure that data can be saved when we don't choose to sort by keys.
- Ignored NA values when computing means of variables.

@santiagohermo, I think we've been forgetting to use `appendlog` argument. Basically, setting it to `FALSE` is needed to overwrite the existing log. I think it would be a good idea to make `FALSE` the default.

@jmshapir, who would be the right person to review the changes here?

**Comment by jmshapir** [comment]
> @jmshapir, who would be the right person to review the changes here?

@veli-m-andirin let's assign @yu-jia-wang and if @yu-jia-wang doesn't have bandwidth we will figure something out.

Thanks!

**Comment by santiagohermo** [comment]
> @santiagohermo, I think we've been forgetting to use `appendlog` argument. Basically, setting it to `FALSE` is needed to overwrite the existing log. I think it would be a good idea to make `FALSE` the default.

About this @veli-m-andirin. We discussed this point with @matthiasweigand earlier. I think the goal was to mimic the behavior of [gslab_stata's `save_data`](https://github.com/gslab-econ/gslab_stata/blob/master/gslab_misc/ado/save_data.ado). I agree though, setting FALSE as default in `appendlog` would be more convenient given the usage we've been giving to the function.

**Comment by jmshapir** [comment]
@veli-m-andirin checking to see if you're ready to open the pull here?

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir for checking-in. I am sorry for the delay here, I have a couple minor changes to make and test per https://github.com/gslab-econ/gslab_r/issues/12#issuecomment-886261900, after which I'll open a PR.

**Comment by jmshapir** [comment]
Thanks @veli-m-andirin, sounds good and no worries! Just wanted to make sure I didn't lose track.

**Comment by veli-m-andirin** [comment]
@jmshapir, I think changes are ready for a PR. Shall I wait for #200 in Skills or open the PR before the discussion there is resolved?

**Comment by jmshapir** [comment]
Might as well open the PR. If we need to make further changes, we can either implement on the same branch (if the pull is still open), or open a new issue (if the pull is wrapped up by then). Thanks!

**Comment by veli-m-andirin** [comment]
Continues in PR #13.

**Comment by veli-m-andirin** [comment]
Summary: In this issue we:

- Added an option to `SaveData()` to allow saving data sorted using different variables instead of the keys.
- Allowed computation of means of numerical variables when there are missing variables.
- Changed the default for `appendlog` to ``FALSE`.
- Modified `SaveData` so that the function breaks when there are rows with missing keys.

Changes were merged to master in d403820.

Final state of the issue branch [here](https://github.com/gslab-econ/gslab_r/tree/7795a6364784acc1d299265c9d55fb1bd1a59c74).
