### ISSUE TITLE
Improve dependency structure for SaveData

### ISSUE THREAD

**Issue by veli-m-andirin** [gslab-econ/gslab_r#21]
Per an e-mail suggestion today from Matthias, we thought that switching to the `packagename::function` convention when calling functions from other packages would avoid bugs in cases where another preloaded package has a function whose name is the same as one of the functions we are calling in SaveData.

[Here](https://github.com/gslab-econ/gslab_r/files/9136581/diff.pdf) are the changes that Matthias suggested. 

One issue is that the unit tests fail when I apply these changes, and I couldn't immediately fix it. @jmshapir, my gslab_r bandwidth over the remaining time may not suffice to complete this issue, so I am not self-assigning, but please let me know if you disagree.

**Comment by jmshapir** [comment]
@matthiasweigand can you please self-assign when you are back in the repo? Thanks!

**Comment by liaochris** [comment]
Taking over this one unless anyone has objections @matthiasweigand

**Comment by liaochris** [comment]
In this issue, we made some updates to [`SaveData.R`](https://github.com/gslab-econ/gslab_r/blob/43558a7a23d25180b2212d2dc21c66d60d240f1c/SaveData/R/SaveData.R) to make the library for each function clear. We also established that these cases are rare and did not appear in the code we changed. 

Latest version of issue branch: https://github.com/gslab-econ/gslab_r/commit/9bbfa7b21b264e701e146c1ad36ed70d9ac008c5
