### ISSUE TITLE
Function for assigning scalars to variables from an input file

### ISSUE THREAD

**Issue by veli-m-andirin** [gslab-econ/gslab_r#25]
In this issue we will write a helper function for assigning scalars to R variables from an input file, i.e. a functionality similar to the one in [loadglob](https://github.com/gslab-econ/gslab_stata/blob/91d2c3bc0acda9334f200d769b69517cb9f3a3fe/gslab_misc/ado/loadglob.ado).

**Comment by ew487** [comment]
@jmshapir I just added a commit for the new function. Would you let me know if this is what you have in mind? Thanks!

**Comment by jmshapir** [comment]
@ew487 thanks and yep, that looks like the right idea! Can you open a pull with @veli-m-andirin @rcalvo12 @jmshapir assigned as reviewers?

(@veli-m-andirin you can skip the review if you like; just wanted to keep you in the loop here, thanks.)

**Comment by ew487** [comment]
Thread continues in its pull request #26

**Comment by ew487** [comment]
**Summary**
In this issue, we added a function `LoadGlobals()` to the GSLabMisc package. The function loads scalars from a .txt file into the global environment in R.

[Link](https://github.com/gslab-econ/gslab_r/tree/601e953eab79d24b6ab3ff5ddebfab3d72b94c5f) to issue branch
Merged to master [here](https://github.com/gslab-econ/gslab_r/commit/2f5d3ac582cec5aa2a29350582059ce4076137a8)
