### ISSUE TITLE
Make SaveData logs friendly to tracking changes on github when adding variables

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_r#31]
When we introduce a new variable to the data that is saved through SaveData, GitHub fails to highlight the changes precisely. For example, below shows the GitHub diff when introducing a new variable `population`.

![image](https://github.com/gslab-econ/gslab_r/assets/84325421/63da2640-49c7-4d92-b335-4ecb88a71ea6)

I think the problem is caused by that the current SaveData logs give each variable an index. Thus, a potential solution is to remove the index (while perhaps output the number of columns in the header)

**Comment by liaochris** [comment]
In this issue, we updated [`SaveData.R`](https://github.com/gslab-econ/gslab_r/blob/6333a62e952acd8d894e40070777993e5a948f9a/SaveData/R/SaveData.R) to make the data summary diff more readable. 
Latest version of issue branch prior to merging: 6333a62e952acd8d894e40070777993e5a948f9a
