### ISSUE TITLE
Bug: SaveData log cannot show correct summary statistics for integer64 variables

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_r#32]
For example: `population` is a variable with max > 0, min > 0, mean >0; however, in line 19: 

![image](https://github.com/gslab-econ/gslab_r/assets/84325421/0c30c316-c1e8-4108-bf4a-b75a612f1806)

**Comment by liaochris** [comment]
@zhizhongpu I'm wondering if the solution is to make everything that's a numeric column of type `as.numeric`.

**Comment by liaochris** [comment]
This issue is no longer relevant for the reasons described in https://github.com/gslab-econ/gslab_r/pull/36#issuecomment-2311267996 and as such is being closed.
