### ISSUE TITLE
SaveData() cannot take list/vector columns

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_r#34]
SaveData() runs into the following error when the input dt/df has list/vector columns:

```
Error: x must be an atomic vector or data.frames/data.tables
Execution halted
```

Here we either force that no list/vector is exported through SaveData() or we accommodate list/vector columns.

**Comment by liaochris** [comment]
We should force that no list/vector is exported through SaveData() in alignment with the python version.

**Comment by liaochris** [comment]
In this issue, we modified `SaveData` to only accept data with columns that are not of type list. 
- Final deliverable:  updated [`SaveData.R`](https://github.com/gslab-econ/gslab_r/blob/1fd50ced9fa2de152587f4f467075982a70808e7/SaveData/R/SaveData.R) and updated [test file ](https://github.com/gslab-econ/gslab_r/blob/1fd50ced9fa2de152587f4f467075982a70808e7/SaveData/tests/testthat/test-SaveData.r)
- Latest version of issue branch: https://github.com/gslab-econ/gslab_r/commit/ab2492732e206058ee6cab317e9270a94979f170
