### ISSUE TITLE
Problem with SaveData for RData output files

### ISSUE THREAD

**Issue by lucamlouzada** [gslab-econ/gslab_r#39]
I'm opening this issue to discuss a problem with [SaveData.R](https://github.com/gslab-econ/gslab_r/blob/master/SaveData/R/SaveData.R) that happens when trying to save data to ".RData" format.

The following code reproduces the error:
```
library(tidyverse)

devtools::install_github("gslab-econ/gslab_r/SaveData", force = TRUE)

# This works
band_instruments %>% 
  SaveData::SaveData("test.csv", key = "name")

# This does not work
band_instruments %>% 
  SaveData::SaveData("test.RData", key = "name")
```

The screenshot below shows the error message:
![image](https://github.com/user-attachments/assets/bedeb702-964e-4ce6-aea4-cfcd16f5ad6a)

I'm tagging @liaochris per our email exchange, but please let me know if there's anyway in which I can help. Thanks!

**Comment by liaochris** [comment]
FYI @zhizhongpu

**Comment by liaochris** [comment]
In this issue we amended [`SaveData`](https://github.com/gslab-econ/gslab_r/blob/39-problem-with-savedata-for-rdata-output-files/SaveData/R/SaveData.R) to work for `.RData` files and amended the tests file

Thanks for catching this @lucamlouzada! 

Latest version of issue branch https://github.com/gslab-econ/gslab_r/tree/2af52eac4394b0c63df17afe89218e419072da4a
Branch merged in https://github.com/gslab-econ/gslab_r/commit/a1dbc76d78a67072a73b8d3ecf19e5b1cf43dfd6
